// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQVb_--TRhCQnKh_AYiQAqPoPbMttaXNc',
    appId: '1:309588220227:web:9be80f4c82bb085da277f6',
    messagingSenderId: '309588220227',
    projectId: 'allinone-schedule-manager',
    authDomain: 'allinone-schedule-manager.firebaseapp.com',
    storageBucket: 'allinone-schedule-manager.appspot.com',
    measurementId: 'G-LNL66H9NLF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmgulZWslsLVuPLH5nQLEq0vFIlcoc1ss',
    appId: '1:309588220227:android:624bfc8e1d9a5564a277f6',
    messagingSenderId: '309588220227',
    projectId: 'allinone-schedule-manager',
    storageBucket: 'allinone-schedule-manager.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBivmkn98z_LVmUf0qEtPWyyPZlCf2oxyc',
    appId: '1:309588220227:ios:7f19f20eaa1f5bf2a277f6',
    messagingSenderId: '309588220227',
    projectId: 'allinone-schedule-manager',
    storageBucket: 'allinone-schedule-manager.appspot.com',
    iosBundleId: 'com.example.betterCalendarApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBivmkn98z_LVmUf0qEtPWyyPZlCf2oxyc',
    appId: '1:309588220227:ios:7f19f20eaa1f5bf2a277f6',
    messagingSenderId: '309588220227',
    projectId: 'allinone-schedule-manager',
    storageBucket: 'allinone-schedule-manager.appspot.com',
    iosBundleId: 'com.example.betterCalendarApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAQVb_--TRhCQnKh_AYiQAqPoPbMttaXNc',
    appId: '1:309588220227:web:dd54512f0d82d34ca277f6',
    messagingSenderId: '309588220227',
    projectId: 'allinone-schedule-manager',
    authDomain: 'allinone-schedule-manager.firebaseapp.com',
    storageBucket: 'allinone-schedule-manager.appspot.com',
    measurementId: 'G-8QHY3X0GZW',
  );
}

//hah linux user (jkjk)
